#! /usr/bin/env python

import subprocess   #module to run system commands
import optparse     #module to handle system commands in a line


def change_mac(interface, new_mac):
    print("[+] Changing the MAC Address of " + interface + "to " + new_mac)

    subprocess.call("ifconfig " + interface + " down", shell=True)
    subprocess.call("ifconfig " + interface + " hw ether " + new_mac, shell=True)
    subprocess.call("ifconfig " + interface + " up", shell=True)


def get_arguments():
    parser = optparse.OptionParser()
    parser.add_option("-i", "--interface", dest="interface", help="interface to change its mac address")
    parser.add_option("-m", "--mac", dest="new_mac", help="new mac to change mac address")
    (options, arguments) = parser.parse_args()


    #This code is only to handle the errors entered by user
    if not options.interface:
        parser.error("[-] Please specify an interface, use --help for more info")
    elif not options.new_mac:
        parser.error("[-] Please specify a new_mac, use --help for more info")
    return options


#Calling both the functions
options = get_arguments()
change_mac(options.interface, options.new_mac)
